### ISSUE TITLE
Include in mono-repo

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store-rspec#1]
What do you think about including it in monorepo as well?

**Comment by paneq** [comment]
My rationale is that most likely you are either

a) using it with aggregate_root gem and its `unpublished_events` so testing compatibility together makes sense imho

or

b) reading from stream or checking an event is in a stream so compatibility with `rails_event_store` makes sense to me as well.

The rationale for merging would be the same as we had with the rest of gems.

**Comment by fidel** [comment]
None of other gems rely on this one, it's just a tooling which you can use if you want to. That's why I decided to keep it out of monorepo.
It's not intended to be used to test RailsEventStore, but use of RailsEventStore integration in someone's app.
